spring:
  data:
    cassandra:
      keyspaceName: ${DB_KEYSPACE:spring_cassandra}
      contactPoints: ${DB_HOST:127.0.0.1}
      port: ${DB_PORT:9042}
      schemaAction: recreate
      local-datacenter: datacenter1
